---
grails:
    profile: web
    codegen:
        defaultPackage: test
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    dialect: MySQL5InnoDBDialect
    pooled: true
    jmxExport: true

environments:
    development:
        dataSource:
            url: jdbc:h2:file:~/.h2
            dbCreate: create-drop
    test:
        dataSource:
            dialect: MySQL5InnoDBDialect
            dbCreate: update
    production:
        dataSource:
              pooled: true
              dbCreate: create-drop
              username: ggrec
              password: LiveMechanics1301
              url: jdbc:mysql://aa1wchy252xpw7.ccmag0pbalsw.us-east-2.rds.amazonaws.com:3306/ebdb
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect
              properties:
                  validationQuery: SELECT 1
                  testOnBorrow: true
                  testOnReturn: true
                  testWhileIdle: true
                  timeBetweenEvictionRunsMillis: 1000 * 60 * 30
                  numTestsPerEvictionRun: 3
                  minEvictableIdleTimeMillis: 1000 * 60 * 30
